# fly.toml app configuration file generated for kiana-server on 2024-02-28T00:45:49-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kiana-server'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
